steps:
- id: 'Fetch cached frontend image'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'pull'
    - 'gcr.io/$PROJECT_ID/cicd-web-cached'

- id: 'Build frontend'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'web'
  args: [
    'build', 
    '--cache-from', 'gcr.io/$PROJECT_ID/cicd-web-cached', 
    '-t', 'gcr.io/$PROJECT_ID/cicd-web:$COMMIT_SHA', 
    '.'
  ]

- id: 'Build backend'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'worker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cicd-worker:$COMMIT_SHA', '.' ]

images:
- 'gcr.io/$PROJECT_ID/cicd-web:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/cicd-worker:$COMMIT_SHA'