apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudcats-worker
  labels:
    app: cloudcats
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudcats
        tier: worker
    spec:
      containers:
      - name: cloudcats-worker
        image: gcr.io/cloudcats-next/ccworker:latest
        imagePullPolicy: Always        
        ports:
        - name: http-server
          containerPort: 8081