apiVersion: v1
kind: Service
metadata:
  name: cloudcats-worker
  labels:
    app: cloudcats
    tier: worker
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: cloudcats
    tier: worker
